import { Beer } from '../types';

// --- 1. HIGH DETAIL CURATED LIST (Best for "Trending" / "Featured") ---
const CURATED_BEERS: Omit<Beer, 'id'>[] = [
  // GLOBAL LAGERS & PILSNERS
  { name: "Stella Artois", brewery: "Stella Artois", type: "Pilsner", abv: "5.0%", emoji: "🍺", description: "A classic Belgian pilsner with a crisp finish." },
  { name: "Heineken", brewery: "Heineken", type: "Lager", abv: "5.0%", emoji: "⭐", description: "The world's most recognizable green bottle." },
  { name: "Corona Extra", brewery: "Grupo Modelo", type: "Lager", abv: "4.6%", emoji: "🍋", description: "Best served ice cold with a lime wedge." },
  { name: "Staropramen", brewery: "Staropramen", type: "Pilsner", abv: "5.0%", emoji: "🇨🇿", description: "The #1 beer from Prague." },
  { name: "Budweiser", brewery: "Anheuser-Busch", type: "Lager", abv: "5.0%", emoji: "👑", description: "The King of Beers." },
  { name: "Pilsner Urquell", brewery: "Plzeňský Prazdroj", type: "Pilsner", abv: "4.4%", emoji: "🥇", description: "The original Pilsner from 1842." },
  { name: "Guinness Draught", brewery: "Guinness", type: "Stout", abv: "4.2%", emoji: "⚫", description: "Dark, creamy, and smooth with a surging head." },
  { name: "Blue Moon", brewery: "Blue Moon Brewing", type: "Wheat Ale", abv: "5.4%", emoji: "🍊", description: "Brewed with orange peel and coriander." },
  { name: "Hoegaarden", brewery: "Brouwerij Hoegaarden", type: "Witbier", abv: "4.9%", emoji: "🌱", description: "The original Belgian wheat beer." },
  { name: "Delirium Tremens", brewery: "Huyghe Brewery", type: "Golden Ale", abv: "8.5%", emoji: "🐘", description: "Famous for its pink elephant logo." },
  { name: "Sierra Nevada Pale Ale", brewery: "Sierra Nevada", type: "Pale Ale", abv: "5.6%", emoji: "🌲", description: "Heavy on hops, mild on malt." },
  { name: "Two Hearted Ale", brewery: "Bell's Brewery", type: "IPA", abv: "7.0%", emoji: "🐟", description: "Ranked best beer in America multiple times." },
  { name: "Lagunitas IPA", brewery: "Lagunitas", type: "IPA", abv: "6.2%", emoji: "🐶", description: "A well-rounded, highly drinkable IPA." },
  { name: "Michelob Ultra", brewery: "Anheuser-Busch", type: "Lager", abv: "4.2%", emoji: "🏃", description: "Superior Light Beer." },
  { name: "Pabst Blue Ribbon", brewery: "Pabst", type: "Lager", abv: "4.8%", emoji: "🎀", description: "The hipster classic." },
];

// --- 2. BULK LIBRARY (Parsed from User PDF/OCR) ---
// Cleaned up names, inferred breweries and styles where possible.
const LIBRARY_BEERS: Omit<Beer, 'id'>[] = [
  // US CRAFT - MICHIGAN & MIDWEST HEAVY
  { name: "Oberon Ale", brewery: "Bell's", type: "Wheat Ale", abv: "5.8%", emoji: "☀️" },
  { name: "Expedition Stout", brewery: "Bell's", type: "Imperial Stout", abv: "10.5%", emoji: "🌌" },
  { name: "Kalamazoo Stout", brewery: "Bell's", type: "Stout", abv: "6.0%", emoji: "☕" },
  { name: "Hopslam Ale", brewery: "Bell's", type: "Double IPA", abv: "10.0%", emoji: "🍯" },
  { name: "Best Brown Ale", brewery: "Bell's", type: "Brown Ale", abv: "5.8%", emoji: "🍂" },
  { name: "Winter White Ale", brewery: "Bell's", type: "Wheat Ale", abv: "5.0%", emoji: "❄️" },
  { name: "Founders Pale Ale", brewery: "Founders", type: "Pale Ale", abv: "5.4%", emoji: "🎨" },
  { name: "Dirty Bastard", brewery: "Founders", type: "Scotch Ale", abv: "8.5%", emoji: "🎸" },
  { name: "Centennial IPA", brewery: "Founders", type: "IPA", abv: "7.2%", emoji: "🌿" },
  { name: "Red Rye IPA", brewery: "Founders", type: "Rye IPA", abv: "6.6%", emoji: "🔴" },
  { name: "Breakfast Stout", brewery: "Founders", type: "Stout", abv: "8.3%", emoji: "☕" },
  { name: "Kentucky Breakfast Stout (KBS)", brewery: "Founders", type: "Imperial Stout", abv: "12.0%", emoji: "🥃" },
  { name: "Devil Dancer", brewery: "Founders", type: "Triple IPA", abv: "12.0%", emoji: "💃" },
  { name: "Rubaeus", brewery: "Founders", type: "Fruit Beer", abv: "5.7%", emoji: "🍇" },
  { name: "Mad Hatter", brewery: "New Holland", type: "IPA", abv: "7.0%", emoji: "🎩" },
  { name: "Dragon's Milk", brewery: "New Holland", type: "Stout", abv: "11.0%", emoji: "🐉" },
  { name: "The Poet", brewery: "New Holland", type: "Oatmeal Stout", abv: "5.2%", emoji: "✒️" },
  { name: "Ichabod", brewery: "New Holland", type: "Pumpkin Ale", abv: "4.5%", emoji: "🎃" },
  { name: "Crooked Tree IPA", brewery: "Dark Horse", type: "IPA", abv: "6.5%", emoji: "🌳" },
  { name: "Raspberry Ale", brewery: "Dark Horse", type: "Fruit Beer", abv: "5.0%", emoji: "🍓" },
  { name: "Scotty Karate", brewery: "Dark Horse", type: "Scotch Ale", abv: "9.75%", emoji: "🥋" },
  { name: "Arcadia IPA", brewery: "Arcadia", type: "IPA", abv: "5.9%", emoji: "🇬🇧" },
  { name: "Anglers Ale", brewery: "Arcadia", type: "Pale Ale", abv: "5.2%", emoji: "🎣" },
  { name: "Whitsun", brewery: "Arcadia", type: "Wheat Ale", abv: "6.2%", emoji: "☀️" },
  { name: "Bam Biere", brewery: "Jolly Pumpkin", type: "Farmhouse Ale", abv: "4.5%", emoji: "🚜" },
  { name: "Oro de Calabaza", brewery: "Jolly Pumpkin", type: "Strong Ale", abv: "8.0%", emoji: "🎃" },
  { name: "La Roja", brewery: "Jolly Pumpkin", type: "Sour Ale", abv: "7.2%", emoji: "🍷" },
  { name: "Edmund Fitzgerald", brewery: "Great Lakes", type: "Porter", abv: "6.0%", emoji: "🚢" },
  { name: "Dortmunder Gold", brewery: "Great Lakes", type: "Lager", abv: "5.8%", emoji: "🥇" },
  { name: "Burning River", brewery: "Great Lakes", type: "Pale Ale", abv: "6.0%", emoji: "🔥" },
  { name: "Christmas Ale", brewery: "Great Lakes", type: "Winter Warmer", abv: "7.5%", emoji: "🎄" },
  { name: "312 Urban Wheat", brewery: "Goose Island", type: "Wheat Ale", abv: "4.2%", emoji: "🏙️" },
  { name: "Honker's Ale", brewery: "Goose Island", type: "Bitter", abv: "4.3%", emoji: "🦢" },
  { name: "Matilda", brewery: "Goose Island", type: "Belgian Ale", abv: "7.0%", emoji: "🧙‍♀️" },
  { name: "Sofie", brewery: "Goose Island", type: "Farmhouse Ale", abv: "6.5%", emoji: "🥂" },
  { name: "Bourbon County Stout", brewery: "Goose Island", type: "Stout", abv: "14.0%", emoji: "🥃" },
  { name: "Point Special", brewery: "Stevens Point", type: "Lager", abv: "4.7%", emoji: "🍺" },
  
  // US CRAFT - NATIONAL
  { name: "90 Minute IPA", brewery: "Dogfish Head", type: "Imperial IPA", abv: "9.0%", emoji: "🦈" },
  { name: "60 Minute IPA", brewery: "Dogfish Head", type: "IPA", abv: "6.0%", emoji: "⏱️" },
  { name: "120 Minute IPA", brewery: "Dogfish Head", type: "Imperial IPA", abv: "18.0%", emoji: "💣" },
  { name: "Midas Touch", brewery: "Dogfish Head", type: "Ancient Ale", abv: "9.0%", emoji: "👑" },
  { name: "Raison D'Etre", brewery: "Dogfish Head", type: "Belgian Strong", abv: "8.0%", emoji: "🍇" },
  { name: "Stone IPA", brewery: "Stone", type: "IPA", abv: "6.9%", emoji: "🗿" },
  { name: "Arrogant Bastard", brewery: "Stone", type: "Strong Ale", abv: "7.2%", emoji: "😈" },
  { name: "Ruination", brewery: "Stone", type: "Double IPA", abv: "8.5%", emoji: "🏚️" },
  { name: "Dead Guy Ale", brewery: "Rogue", type: "Maibock", abv: "6.8%", emoji: "☠️" },
  { name: "Hazelnut Brown Nectar", brewery: "Rogue", type: "Brown Ale", abv: "5.6%", emoji: "🌰" },
  { name: "Brutal Bitter", brewery: "Rogue", type: "Bitter", abv: "6.2%", emoji: "😠" },
  { name: "Torpedo Extra IPA", brewery: "Sierra Nevada", type: "IPA", abv: "7.2%", emoji: "🚀" },
  { name: "Celebration Ale", brewery: "Sierra Nevada", type: "IPA", abv: "6.8%", emoji: "🎉" },
  { name: "Bigfoot", brewery: "Sierra Nevada", type: "Barleywine", abv: "9.6%", emoji: "👣" },
  { name: "Fat Tire", brewery: "New Belgium", type: "Amber Ale", abv: "5.2%", emoji: "🚲" },
  { name: "Voodoo Ranger", brewery: "New Belgium", type: "IPA", abv: "7.0%", emoji: "💀" },
  { name: "Sam Adams Boston Lager", brewery: "Boston Beer Co.", type: "Lager", abv: "5.0%", emoji: "🇺🇸" },
  { name: "Sam Adams Winter Lager", brewery: "Boston Beer Co.", type: "Bock", abv: "5.6%", emoji: "❄️" },
  { name: "Sam Adams Octoberfest", brewery: "Boston Beer Co.", type: "Marzen", abv: "5.3%", emoji: "🍂" },
  { name: "Sam Adams Summer Ale", brewery: "Boston Beer Co.", type: "Wheat Ale", abv: "5.3%", emoji: "🍋" },
  { name: "Cherry Wheat", brewery: "Boston Beer Co.", type: "Fruit Beer", abv: "5.3%", emoji: "🍒" },
  { name: "Utopias", brewery: "Boston Beer Co.", type: "Strong Ale", abv: "28.0%", emoji: "⚱️" },
  { name: "Magic Hat #9", brewery: "Magic Hat", type: "Pale Ale", abv: "5.1%", emoji: "🎩" },
  { name: "Long Hammer IPA", brewery: "Redhook", type: "IPA", abv: "6.2%", emoji: "🔨" },
  { name: "Shiner Bock", brewery: "Spoetzl", type: "Bock", abv: "4.4%", emoji: "🐏" },
  { name: "Abita Amber", brewery: "Abita", type: "Amber Ale", abv: "4.5%", emoji: "⚜️" },
  { name: "Purple Haze", brewery: "Abita", type: "Fruit Beer", abv: "4.2%", emoji: "🟣" },
  { name: "Turbo Dog", brewery: "Abita", type: "Brown Ale", abv: "5.6%", emoji: "🐕" },
  { name: "Anchor Steam", brewery: "Anchor", type: "Steam Beer", abv: "4.9%", emoji: "⚓" },
  { name: "Liberty Ale", brewery: "Anchor", type: "IPA", abv: "5.9%", emoji: "🗽" },
  { name: "Old Foghorn", brewery: "Anchor", type: "Barleywine", abv: "8.8%", emoji: "📯" },
  { name: "Lagunitas Maximus", brewery: "Lagunitas", type: "Double IPA", abv: "8.2%", emoji: "🏛️" },
  { name: "Brown Shugga", brewery: "Lagunitas", type: "Strong Ale", abv: "9.9%", emoji: "🍬" },
  { name: "Little Sumpin' Sumpin'", brewery: "Lagunitas", type: "Wheat Ale", abv: "7.5%", emoji: "💃" },
  { name: "Avery IPA", brewery: "Avery", type: "IPA", abv: "6.5%", emoji: "🅰️" },
  { name: "White Rascal", brewery: "Avery", type: "Witbier", abv: "5.6%", emoji: "👻" },
  { name: "Maharaja", brewery: "Avery", type: "Imperial IPA", abv: "10.0%", emoji: "🤴" },
  { name: "HopDevil", brewery: "Victory", type: "IPA", abv: "6.7%", emoji: "😈" },
  { name: "Prima Pils", brewery: "Victory", type: "Pilsner", abv: "5.3%", emoji: "🥬" },
  { name: "Golden Monkey", brewery: "Victory", type: "Tripel", abv: "9.5%", emoji: "🐒" },
  { name: "Storm King", brewery: "Victory", type: "Stout", abv: "9.1%", emoji: "⛈️" },
  { name: "Harpoon IPA", brewery: "Harpoon", type: "IPA", abv: "5.9%", emoji: "🐳" },
  { name: "UFO White", brewery: "Harpoon", type: "Witbier", abv: "4.8%", emoji: "🛸" },
  { name: "Boont Amber", brewery: "Anderson Valley", type: "Amber Ale", abv: "5.8%", emoji: "🐻" },
  { name: "Winter Solstice", brewery: "Anderson Valley", type: "Winter Warmer", abv: "6.9%", emoji: "❄️" },

  // IMPORTS - EUROPE
  { name: "London Pride", brewery: "Fuller's", type: "Ale", abv: "4.7%", emoji: "🦁" },
  { name: "Fuller's ESB", brewery: "Fuller's", type: "Bitter", abv: "5.9%", emoji: "🇬🇧" },
  { name: "London Porter", brewery: "Fuller's", type: "Porter", abv: "5.4%", emoji: "🌑" },
  { name: "Samuel Smith Oatmeal Stout", brewery: "Samuel Smith", type: "Stout", abv: "5.0%", emoji: "🥣" },
  { name: "Taddy Porter", brewery: "Samuel Smith", type: "Porter", abv: "5.0%", emoji: "📦" },
  { name: "Nut Brown Ale", brewery: "Samuel Smith", type: "Brown Ale", abv: "5.0%", emoji: "🥜" },
  { name: "Organic Lager", brewery: "Samuel Smith", type: "Lager", abv: "5.0%", emoji: "🌱" },
  { name: "Bass Ale", brewery: "Bass", type: "Pale Ale", abv: "5.1%", emoji: "🔺" },
  { name: "Boddingtons", brewery: "InBev", type: "Cream Ale", abv: "3.5%", emoji: "🐝" },
  { name: "Newcastle Brown Ale", brewery: "Heineken", type: "Brown Ale", abv: "4.7%", emoji: "🌉" },
  { name: "Old Speckled Hen", brewery: "Morland", type: "Ale", abv: "5.0%", emoji: "🐔" },
  { name: "Skull Splitter", brewery: "Orkney", type: "Scotch Ale", abv: "8.5%", emoji: "💀" },
  { name: "Duvel", brewery: "Duvel Moortgat", type: "Golden Ale", abv: "8.5%", emoji: "😈" },
  { name: "Chimay Blue (Grande Réserve)", brewery: "Chimay", type: "Trappist", abv: "9.0%", emoji: "🔵" },
  { name: "Chimay Red (Première)", brewery: "Chimay", type: "Trappist", abv: "7.0%", emoji: "🔴" },
  { name: "Chimay White (Cinq Cents)", brewery: "Chimay", type: "Trappist", abv: "8.0%", emoji: "⚪" },
  { name: "Leffe Blonde", brewery: "Leffe", type: "Abbey Ale", abv: "6.6%", emoji: "⛪" },
  { name: "Leffe Brune", brewery: "Leffe", type: "Abbey Ale", abv: "6.5%", emoji: "🟤" },
  { name: "Westmalle Tripel", brewery: "Westmalle", type: "Trappist", abv: "9.5%", emoji: "⛪" },
  { name: "Rochefort 10", brewery: "Rochefort", type: "Trappist", abv: "11.3%", emoji: "🔟" },
  { name: "Orval", brewery: "Orval", type: "Trappist", abv: "6.2%", emoji: "🐟" },
  { name: "Saison Dupont", brewery: "Brasserie Dupont", type: "Saison", abv: "6.5%", emoji: "🌾" },
  { name: "La Chouffe", brewery: "Achouffe", type: "Blonde Ale", abv: "8.0%", emoji: "🍄" },
  { name: "Delirium Nocturnum", brewery: "Huyghe", type: "Dark Ale", abv: "8.5%", emoji: "🐘" },
  { name: "Lindemans Framboise", brewery: "Lindemans", type: "Lambic", abv: "2.5%", emoji: "🍓" },
  { name: "Paulaner Hefe-Weizen", brewery: "Paulaner", type: "Wheat Beer", abv: "5.5%", emoji: "🇩🇪" },
  { name: "Paulaner Salvator", brewery: "Paulaner", type: "Doppelbock", abv: "7.9%", emoji: "🐐" },
  { name: "Weihenstephaner Hefe Weissbier", brewery: "Weihenstephaner", type: "Wheat Beer", abv: "5.4%", emoji: "🏰" },
  { name: "Franziskaner", brewery: "Spaten", type: "Wheat Beer", abv: "5.0%", emoji: "🧔" },
  { name: "Spaten Oktoberfest", brewery: "Spaten", type: "Marzen", abv: "5.9%", emoji: "🎪" },
  { name: "Spaten Optimator", brewery: "Spaten", type: "Doppelbock", abv: "7.6%", emoji: "💪" },
  { name: "Warsteiner", brewery: "Warsteiner", type: "Pilsner", abv: "4.8%", emoji: "🛡️" },
  { name: "Bitburger", brewery: "Bitburger", type: "Pilsner", abv: "4.8%", emoji: "🍺" },
  { name: "Beck's", brewery: "Beck's", type: "Pilsner", abv: "5.0%", emoji: "🔑" },
  { name: "St. Pauli Girl", brewery: "St. Pauli", type: "Lager", abv: "4.9%", emoji: "💃" },
  { name: "Hofbräu Original", brewery: "Hofbräuhaus", type: "Helles", abv: "5.1%", emoji: "🏫" },
  { name: "Kostritzer Schwarzbier", brewery: "Kostritzer", type: "Dark Lager", abv: "4.8%", emoji: "🌑" },
  { name: "Aventinus", brewery: "Schneider Weisse", type: "Doppelbock", abv: "8.2%", emoji: "🟣" },
  { name: "Moretti", brewery: "Birra Moretti", type: "Lager", abv: "4.6%", emoji: "🇮🇹" },
  { name: "Peroni Nastro Azzurro", brewery: "Peroni", type: "Lager", abv: "5.1%", emoji: "🔵" },
  { name: "Grolsch", brewery: "Grolsch", type: "Pilsner", abv: "5.0%", emoji: "🟢" },
  { name: "Amstel Light", brewery: "Amstel", type: "Lager", abv: "3.5%", emoji: "🛶" },
  { name: "Kronenbourg 1664", brewery: "Kronenbourg", type: "Lager", abv: "5.0%", emoji: "🇫🇷" },
  { name: "Unibrew La Fin Du Monde", brewery: "Unibroue", type: "Tripel", abv: "9.0%", emoji: "🇨🇦" },
  { name: "Unibrew Maudite", brewery: "Unibroue", type: "Strong Ale", abv: "8.0%", emoji: "😈" },
  { name: "Unibrew Trois Pistoles", brewery: "Unibroue", type: "Strong Dark", abv: "9.0%", emoji: "🔫" },
  { name: "Molson Canadian", brewery: "Molson", type: "Lager", abv: "5.0%", emoji: "🍁" },
  { name: "Molson Golden", brewery: "Molson", type: "Ale", abv: "5.0%", emoji: "🥇" },
  { name: "Labatt Blue", brewery: "Labatt", type: "Pilsner", abv: "5.0%", emoji: "🔵" },
  { name: "Moosehead", brewery: "Moosehead", type: "Lager", abv: "5.0%", emoji: "🦌" },
  
  // IMPORTS - WORLD
  { name: "Corona Light", brewery: "Grupo Modelo", type: "Lager", abv: "4.1%", emoji: "☀️" },
  { name: "Modelo Especial", brewery: "Grupo Modelo", type: "Pilsner", abv: "4.4%", emoji: "🦁" },
  { name: "Negra Modelo", brewery: "Grupo Modelo", type: "Dunkel", abv: "5.4%", emoji: "🍫" },
  { name: "Pacifico", brewery: "Grupo Modelo", type: "Pilsner", abv: "4.5%", emoji: "🌊" },
  { name: "Dos Equis Lager", brewery: "Cuauhtémoc Moctezuma", type: "Lager", abv: "4.2%", emoji: "❌" },
  { name: "Dos Equis Amber", brewery: "Cuauhtémoc Moctezuma", type: "Vienna Lager", abv: "4.7%", emoji: "🟧" },
  { name: "Tecate", brewery: "Cuauhtémoc Moctezuma", type: "Lager", abv: "4.5%", emoji: "🦅" },
  { name: "Sol", brewery: "Cuauhtémoc Moctezuma", type: "Lager", abv: "4.5%", emoji: "🌞" },
  { name: "Red Stripe", brewery: "Desnoes & Geddes", type: "Lager", abv: "4.7%", emoji: "🇯🇲" },
  { name: "Foster's", brewery: "Carlton & United", type: "Lager", abv: "5.0%", emoji: "🇦🇺" },
  { name: "Tsingtao", brewery: "Tsingtao", type: "Lager", abv: "4.7%", emoji: "🇨🇳" },
  { name: "Sapporo", brewery: "Sapporo", type: "Lager", abv: "4.9%", emoji: "⭐" },
  { name: "Kirin Ichiban", brewery: "Kirin", type: "Lager", abv: "5.0%", emoji: "🐉" },
  { name: "Asahi Super Dry", brewery: "Asahi", type: "Lager", abv: "5.0%", emoji: "🇯🇵" },
  { name: "Singha", brewery: "Boon Rawd", type: "Lager", abv: "5.0%", emoji: "🦁" },
  { name: "Tiger", brewery: "Heineken Asia", type: "Lager", abv: "5.0%", emoji: "🐯" },

  // DOMESTICS / MACRO
  { name: "Bud Light", brewery: "Anheuser-Busch", type: "Light Lager", abv: "4.2%", emoji: "🔵" },
  { name: "Bud Ice", brewery: "Anheuser-Busch", type: "Ice Lager", abv: "5.5%", emoji: "🧊" },
  { name: "Bud Select", brewery: "Anheuser-Busch", type: "Light Lager", abv: "4.3%", emoji: "👑" },
  { name: "Busch", brewery: "Anheuser-Busch", type: "Lager", abv: "4.3%", emoji: "🌲" },
  { name: "Busch Light", brewery: "Anheuser-Busch", type: "Light Lager", abv: "4.1%", emoji: "🏔️" },
  { name: "Michelob Light", brewery: "Anheuser-Busch", type: "Light Lager", abv: "4.1%", emoji: "🎀" },
  { name: "Michelob Ultra Amber", brewery: "Anheuser-Busch", type: "Light Lager", abv: "4.0%", emoji: "🟧" },
  { name: "Natural Light", brewery: "Anheuser-Busch", type: "Light Lager", abv: "4.2%", emoji: "📉" },
  { name: "Natural Ice", brewery: "Anheuser-Busch", type: "Ice Lager", abv: "5.9%", emoji: "❄️" },
  { name: "Rolling Rock", brewery: "Anheuser-Busch", type: "Lager", abv: "4.4%", emoji: "🟢" },
  { name: "Shock Top", brewery: "Anheuser-Busch", type: "Wheat Ale", abv: "5.2%", emoji: "🍊" },
  { name: "Miller Lite", brewery: "Miller", type: "Light Lager", abv: "4.2%", emoji: "🏳️" },
  { name: "Miller High Life", brewery: "Miller", type: "Lager", abv: "4.6%", emoji: "🥂" },
  { name: "Miller Genuine Draft (MGD)", brewery: "Miller", type: "Lager", abv: "4.6%", emoji: "🦅" },
  { name: "Milwaukee's Best", brewery: "Miller", type: "Lager", abv: "4.3%", emoji: "🐗" },
  { name: "Icehouse", brewery: "Miller", type: "Ice Lager", abv: "5.5%", emoji: "🏠" },
  { name: "Olde English 800", brewery: "Miller", type: "Malt Liquor", abv: "5.9%", emoji: "🇬🇧" },
  { name: "Coors Light", brewery: "Coors", type: "Light Lager", abv: "4.2%", emoji: "🏔️" },
  { name: "Coors Banquet", brewery: "Coors", type: "Lager", abv: "5.0%", emoji: "🤠" },
  { name: "Keystone Light", brewery: "Coors", type: "Light Lager", abv: "4.1%", emoji: "🟦" },
  { name: "Blue Moon Belgian White", brewery: "Blue Moon", type: "Wheat Ale", abv: "5.4%", emoji: "🌙" },
  { name: "Killian's Irish Red", brewery: "Coors", type: "Red Ale", abv: "4.9%", emoji: "🐴" },
  { name: "Steel Reserve", brewery: "Steel Brewing", type: "Malt Liquor", abv: "8.1%", emoji: "🏗️" },
  { name: "Yuengling Traditional Lager", brewery: "Yuengling", type: "Lager", abv: "4.5%", emoji: "🦅" },
  { name: "Old Style", brewery: "Pabst", type: "Lager", abv: "4.6%", emoji: "⚾" },
  { name: "Colt 45", brewery: "Pabst", type: "Malt Liquor", abv: "6.1%", emoji: "🐎" },
  { name: "Schlitz", brewery: "Pabst", type: "Lager", abv: "4.6%", emoji: "🐂" },
  { name: "Stroh's", brewery: "Pabst", type: "Lager", abv: "4.5%", emoji: "🦁" },

  // CIDERS & ALT (From List)
  { name: "Woodchuck Amber", brewery: "Woodchuck", type: "Cider", abv: "5.0%", emoji: "🐿️" },
  { name: "Angry Orchard", brewery: "Boston Beer Co.", type: "Cider", abv: "5.0%", emoji: "🍎" },
  { name: "Strongbow", brewery: "Bulmers", type: "Cider", abv: "5.0%", emoji: "🏹" },
  { name: "Magners", brewery: "C&C Group", type: "Cider", abv: "4.5%", emoji: "🍏" },
  { name: "Mike's Hard Lemonade", brewery: "Mike's", type: "Malt Beverage", abv: "5.0%", emoji: "🍋" },
  { name: "Smirnoff Ice", brewery: "Diageo", type: "Malt Beverage", abv: "4.5%", emoji: "🧊" },
  { name: "Twisted Tea", brewery: "Twisted Tea", type: "Hard Tea", abv: "5.0%", emoji: "🍵" }
];

// Combine and deduplicate based on name
const uniqueBeersMap = new Map<string, Omit<Beer, 'id'>>();
[...CURATED_BEERS, ...LIBRARY_BEERS].forEach(beer => {
  uniqueBeersMap.set(beer.name, beer);
});

export const STATIC_BEERS = Array.from(uniqueBeersMap.values());